"""Initial schema setup

Revision ID: 786c064f20a6
Revises: 
Create Date: 2026-05-31 19:14:18.157110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786c064f20a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_case_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_case_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_run_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_run_user_id'))
        batch_op.drop_index(batch_op.f('ix_test_run_timestamp'))

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_case_user_id'))
        batch_op.drop_index(batch_op.f('ix_test_case_timestamp'))

    # ### end Alembic commands ###
